import { MatListModule, MatDialogModule, MatTooltipModule, MatRadioModule, MatInputModule, MatFormFieldModule, MatCheckboxModule, MatNativeDateModule, MatDatepickerModule, MatCardModule, MatSelectModule, MatButtonModule, MatAutocompleteModule, MatChipsModule, MatDividerModule, MatExpansionModule, MatGridListModule, MatIconModule, MatMenuModule, MatPaginatorModule, MatProgressBarModule, MatProgressSpinnerModule, MatRippleModule, MatSidenavModule, MatSliderModule, MatSlideToggleModule, MatSnackBarModule, MatSortModule, MatStepperModule, MatTableModule, MatTabsModule, MatToolbarModule } from "@angular/material";
import { NgModule } from "@angular/core";



@NgModule({
    imports: [
      MatListModule,
      MatDialogModule, 
      MatTooltipModule, 
      MatRadioModule,
      MatInputModule,
      MatFormFieldModule,
      MatCheckboxModule, 
      MatNativeDateModule , 
      MatDatepickerModule, 
      MatCardModule, 
      MatSelectModule, 
      MatButtonModule, 
      MatAutocompleteModule,
      MatChipsModule,
      MatDividerModule,
      MatExpansionModule,
      MatGridListModule,
      MatIconModule,
      MatMenuModule,
      MatPaginatorModule,
      MatProgressBarModule,
      MatProgressSpinnerModule,
      MatRippleModule,
      MatSidenavModule,
      MatSliderModule,
      MatSlideToggleModule,
      MatSnackBarModule,
      MatSortModule,
      MatStepperModule,
      MatTableModule,
      MatTabsModule,
      MatToolbarModule,
      MatTooltipModule,],
  
  
    exports: [MatListModule,
      MatDialogModule, 
      MatTooltipModule, 
      MatRadioModule,
      MatInputModule,
      MatFormFieldModule,
      MatCheckboxModule, 
      MatDatepickerModule, 
      MatCardModule, 
      MatSelectModule, 
      MatButtonModule, 
      MatAutocompleteModule,
      MatChipsModule,
      MatDividerModule,
      MatExpansionModule,
      MatGridListModule,
      MatIconModule,
      MatMenuModule,
      MatPaginatorModule,
      MatProgressBarModule,
      MatProgressSpinnerModule,
      MatRippleModule,
      MatSidenavModule,
      MatSliderModule,
      MatSlideToggleModule,
      MatSnackBarModule,
      MatSortModule,
      MatStepperModule,
      MatTableModule,
      MatTabsModule,
      MatToolbarModule,
      MatTooltipModule,
    ],
  })

  export class MaterialModule {
}

